# Generated by Django 4.0.6 on 2023-04-03 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Whiteboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="WhiteboardPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="whiteboard.whiteboard",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="whiteboard",
            name="players",
            field=models.ManyToManyField(
                related_name="players", to="whiteboard.whiteboardplayer"
            ),
        ),
    ]
