# Generated by Django 4.0.6 on 2023-04-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whiteboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="whiteboard",
            name="total_players",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
