# Generated by Django 4.0.6 on 2022-12-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room", models.CharField(max_length=100)),
                ("host", models.CharField(max_length=100)),
                ("opponent", models.CharField(blank=True, max_length=100, null=True)),
                ("is_over", models.BooleanField(default=False)),
            ],
        ),
    ]
