# Generated by Django 4.0.6 on 2023-02-02 00:09

import django.db.models.deletion
from django.db import migrations, models

import tictactoe.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TicTacToeRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(max_length=50)),
                (
                    "board_state",
                    models.JSONField(default=tictactoe.models.default_board_state),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrackPlayers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tictactoe.tictactoeroom",
                    ),
                ),
            ],
        ),
    ]
