# Generated by Django 4.0.6 on 2022-12-28 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tictactoe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicTacToeRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="TrackPlayers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tictactoe.tictactoeroom",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Game",
        ),
    ]
