# Generated by Django 4.0.6 on 2023-02-08 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tictactoe",
            "0002_tictactoeplayer_is_active_tictactoeplayer_is_player_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tictactoeroom",
            name="players_turn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players_turn",
                to="tictactoe.tictactoeplayer",
            ),
        ),
        migrations.AlterField(
            model_name="tictactoeroom",
            name="players",
            field=models.ManyToManyField(
                limit_choices_to={"is_player": True},
                related_name="players",
                to="tictactoe.tictactoeplayer",
            ),
        ),
    ]
