# Generated by Django 4.0.6 on 2023-03-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tictactoe", "0003_tictactoeroom_players_turn_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tictactoeplayer",
            name="is_player",
        ),
        migrations.AddField(
            model_name="tictactoeplayer",
            name="is_winner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tictactoeroom",
            name="game_state",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tictactoeroom",
            name="total_players",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tictactoeroom",
            name="players",
            field=models.ManyToManyField(
                related_name="players", to="tictactoe.tictactoeplayer"
            ),
        ),
    ]
