# Generated by Django 4.0.6 on 2023-01-28 22:36

from django.db import migrations, models

import tictactoe.models


class Migration(migrations.Migration):

    dependencies = [
        ("tictactoe", "0003_alter_trackplayers_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="tictactoeroom",
            name="board_state",
            field=models.JSONField(default=tictactoe.models.default_board_state),
        ),
    ]
