# Generated by Django 4.0.6 on 2023-03-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tictactoe", "0005_tictactoeplayer_figure"),
    ]

    operations = [
        migrations.AddField(
            model_name="tictactoeplayer",
            name="is_ready",
            field=models.BooleanField(default=False),
        ),
    ]
