# Generated by Django 4.0.6 on 2023-03-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FifteenPuzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("board_state", models.JSONField(default=list)),
                ("game_state", models.BooleanField(default=False)),
                ("moves", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
