# Generated by Django 4.0.6 on 2023-03-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fifteen", "0002_remove_fifteenpuzzle_game_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="fifteenpuzzle",
            name="game_state",
            field=models.BooleanField(default=False),
        ),
    ]
