# Generated by Django 4.0.6 on 2023-02-04 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TrackPlayers",
            new_name="BingoPlayer",
        ),
    ]
