# Generated by Django 4.0.6 on 2023-02-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bingoroom",
            name="board_state",
            field=models.JSONField(default=list),
        ),
    ]
