# Generated by Django 4.0.6 on 2023-01-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackplayers",
            name="is_winner",
            field=models.BooleanField(default=False),
        ),
    ]
