# Generated by Django 4.0.6 on 2023-02-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bingo", "0002_bingoroom_board_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="bingoplayer",
            name="initial_board_state",
            field=models.JSONField(default=list),
        ),
    ]
