# Generated by Django 4.0.6 on 2023-02-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0003_bingoplayer_initial_board_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="bingoplayer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
