# Generated by Django 4.0.6 on 2023-02-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0005_bingoplayer_is_player_bingoroom_players_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bingoplayer",
            name="is_player",
        ),
        migrations.AddField(
            model_name="bingoroom",
            name="total_players",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bingoroom",
            name="players",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"is_player": True},
                related_name="players",
                to="bingo.bingoplayer",
            ),
        ),
    ]
