# Generated by Django 4.0.6 on 2023-03-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bingo", "0007_alter_bingoroom_players"),
    ]

    operations = [
        migrations.AddField(
            model_name="bingoroom",
            name="game_state",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bingoroom",
            name="players",
            field=models.ManyToManyField(
                related_name="players", to="bingo.bingoplayer"
            ),
        ),
    ]
