# Generated by Django 4.0.6 on 2023-03-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bingo", "0008_bingoroom_game_state_alter_bingoroom_players"),
    ]

    operations = [
        migrations.AddField(
            model_name="bingoplayer",
            name="is_ready",
            field=models.BooleanField(default=False),
        ),
    ]
